#define error_with_calculate_hash 			1
#define error_with_calculate_signature_size 2
#define error_with_calculate_signature 		3
#define error_with_get_user_name 			4
#define error_with_get_computer_name 		5
#define error_with_get_windows_path 		6
#define error_with_get_system_path 			7
#define error_with_get_disk_capacity 		8
#define error_with_get_current_directory 	9
#define error_invalid_disk_label 			10
#define error_with_create_or_open_reg_key 	11
#define error_with_set_reg_key_value 		12
#define error_with_get_reg_key_size 		13
#define error_with_get_reg_key_value 		14
#define error_with_create_process 			15
#define error_with_delete_file 				16
#define error_invalid_resources_path		17
#define error_invalid_resource_name     	18
#define error_with_save_app					19
